access-control.yaml

This PR aims to consolidate the access control list based on issues previously raised in this repo
Fixes #32, #30, #24
- removes erroneous groups mlkem-c-generic-maintainers
- corrected a little confusion between the generic & embedded teams
- removes reference to o-documentation repo (we should delete)
- adds new group pcp-docs-* (assigned for documentation, .github & templates)
- adds new group pqcp-tsc* for tsc (as not formed, set doug as admin)
- corrected roles, so that a contributor team has 'read' access 
- added Norman Ashley to appropriate teams 
Caveats
- have left myself as admin on most of the groups - just as we're getting up to speed with clowarden. these should be removed 
- I presume team maintainers are also members. So I could remove duplicates? @ryjones 
I think the …

#32 Consolidate access control list

---

members/index.md

I'd like to propose Hanno Becker from AWS as an additional TSC member. He is going to join me in maintaining https://github.com/pq-code-package/mlkem-c-aarch64.

Add Hanno Becker to TSC members

---

config.yaml

rod-chapman has been making various contributions to mlkem-c-aarch64 and it would be great if he could also review other pull requests. My understanding is that adding him to the pqcp-contributors would allow that.

Add rod-chapman to pqcp-contributors

---

meetings/2024-08-29/minutes.md
meetings/index.md

* Agenda
* Minutes added 20240911

TSC 20240829 - minutes

---

CODEOWNERS
config.yaml

For some of the CI to work in https://github.com/pq-code-package/mlkem-c-aarch64, the PRs need to come from a local branch. @rod-chapman should be granted the rights to do so - my understand is that creating branches requires at least `write` permissions. 
I used the opportunity to rework the permissions for the mlkem-c-aarch64 repo, as they have been mixed with the mlkem-embedded project as some team members overlap.
Now there are 3 roles: 
- `pqcp-c-aarch64-maintainers` (`maintain` permission) containing the maintainers as before (@hanno-becker, @cothan, @mkannwischer) 
- `pqcp-c-aarch64-contributors` (`write` permission) containins @rod-chapman, @potsrevennil
- `pqcp-c-aarch64-admin` as a copy of the previous `pqcp-embedded-admin`
@hanno-becker, @cothan, could you please have a look if …

Re-work mlkem-c-aarch64 permissions

---

config.yaml

@cothan will move to a contributor role for mlkem-c-aarch64 leaving @hanno-becker and me as the maintainers. 
@cothan, thank you for your help with getting this project started! Please approve this PR if you agree with this change.
@hanno-becker, please approve.

Move cothan from maintainer to contributor for mlkem-c-aarch64 

---

config.yaml

Rename mlkem-c-aarch64 to mlkem-native

---

meetings/2024-10-24/minutes.md
meetings/2024-11-07/minutes.md
meetings/index.md

Signed-off-by: Nigel Jones <jonesn@uk.ibm.com>

Minutes from 20241024 & agenda for 20241107

---

config.yaml

This adds @dkostic (Dusan Kostic, AWS) as a contributor to mlkem-native. 
It also makes @hanno-becker (Hanno Becker, AWS) admin of mlkem-native so he can manage all configuraton of mlkem-native. 
@hanno-becker, please approve. 
@planetf1, please merge once approved.

Add dkostic as mlkem-native contributor; make hanno-becker mlkem-native admin

---

meetings/2024-12-05/minutes.md

TSC 20241205 minutes

---

members/index.md

With @praveksharma on the PQCP TSC, we have a great liaison between OQS and PQCP, so I think it's time for me to resign from the PQCP TSC and avoid messing up your quorum threshold. I'm really impressed with the great work that's developed, especially how well mlkem-native has come together.  (In fact I used mlkem-native in a research project yesterday!)  Keep up the good work!  And do ping me if there's anything I can do to help in the future.

Remove Douglas Stebila from TSC

---

meetings/2025-01-30/minutes.md
meetings/2025-02-13/minutes.md
meetings/index.md

This adds the minutes for the last meeting & agenda for today's meeting.

Add minutes for 20250130 and agenda for 20250213

---

config.yaml

This adds @manastasova (AWS) as a contributor to https://github.com/pq-code-package/mldsa-native. 
@hanno-becker or @jakemas, please approve.

Add @manastasova as mldsa-native contributor

---

config.yaml

I have a new team member Yong-Zhe Zhao (Willie, @willieyz) who will be supporting us with mlkem-native and mldsa-native.
@hanno-becker, @jakemas could you please approve adding Willie?

Add willieyz as contributor to mlkem-native and mldsa-native

---

config.yaml

This commit adds @mjosaarinen (Markku-Juhani O. Saarinen, Tampere University) as a contributor to mlkem-native and mldsa-native. He will be helping us with RISC-V vector backends.

Add mjosaarinen to mlkem-native/mldsa-native

---

config.yaml

Signed-off-by: Nigel Jones <jonesn@uk.ibm.com>
This PR grants maintain access to the current TSC voting members which allows them to assign/manage reviews and merge PRs

Add TSC voting members to pqcp-tsc-maintainers group (maintain on tsc repo)

---

config.yaml

Given that I am not actively involved in PQCP any more, it is okay with me to remove me from having admin/maintainer permissions on the repos.

Remove dstebila from admin/maintainers lists

---

meetings/2025-05-08/minutes.md
meetings/2025-05-22/minutes.md
meetings/index.md

Add minutes for 20250508

---

config.yaml

This commit adds Chun-Ming Chiu as a contributor to mldsa-native. Chun-Ming was selected for the mldsa-native LFX mentorship supervised by myself for the fall 2025 term.

Add Chun-Ming Chiu (jammychiou1)  to mldsa-native/pqcp

---

meetings/2025-07-03/minutes.md
meetings/index.md

Meeting minutes from the 2025-07-03 meeting.
The notes are generated from the transcript using Amazon Q, but I edited everything that was wrong.

2025-07-03 TSC meeting minutes 
