access-control.yaml
=> Create mlkem-c-aarch64 ACLs

README.md, meetings/2024-04-00/agenda.md, meetings/index.md
Adds initial draft agenda for kickoff meeting
=> Add initial draft agenda for first meeting

README.md, members/index.md
This PR adds the initial list of TSC members
Please review and comment if there's any noticeable omissions/suggestions  as per #1 
Fixes #1
=> Add initial list of TSC members

config.yaml
=> Add Hanno Becker

meetings/2024-05-09/minutes.md, meetings/index.md
Initial version of the minutes from the first TSC meeting on 2024-05-09
=> 2024-05-09 minutes

meetings/2024-05-23/agenda.md, meetings/index.md
Adds agenda for 2024-05-23
Please comment with any corrections/additions
=> Add 20240523 agenda

members/index.md
Updates TSC members page with
- reference to TSC lead
- link to docs website for more info
=> Update tsc and pqca info plus improve landing page

meetings/index.md
Correction to bad link in minutes (not spotted in review)
Will merge immediately to avoid broken link
=> Correct link to 2024-05-23 minutes

meetings/2024-06-06/minutes.md, meetings/index.md
TSC meeting minutes from 6 Jun 2024
=> 20240606 minutes

meetings/2024-07-04/minutes.md, meetings/index.md
Signed-off-by: Nigel Jones <jonesn@uk.ibm.com>
=> 20240704 agenda added

meetings/2024-06-06/minutes.md, meetings/2024-06-20/minutes.md
First draft of meeting minutes form our last TSC meeting
Please review.
=> minutes of 20240620 tsc meeting

meetings/2024-07-04/minutes.md
Minutes from previous pq-code-package meeting on 2024-07-04
Please review and note any corrections/omissions.
=> 20240704 minutes

meetings/2024-07-18/minutes.md, meetings/index.md
Please add comments for any additional agenda items to discuss during our next call on 18 July.
Thanks
=> 20240718 initial agenda

meetings/2024-07-18/minutes.md
Adding agenda item for #4 (thanks @franziskuskiefer )
=> Add discussion on TSC issue 4 to agenda

meetings/2024-09-26/minutes.md, meetings/2024-10-10/minutes.md, meetings/index.md
Minutes from 20240926
Template agenda for 20241010
=> Minutes 20240926 and agenda 20241010

meetings/2024-09-26/minutes.md, meetings/2024-10-10/minutes.md, meetings/2024-10-24/minutes.md, meetings/index.md
* Minutes from 20241010
* Agenda for 20241024
Any corrections please raise issue - I will merge prior to the meeting. (apologies for late update)
=> minutes of 20241010 tsc meeting

config.yaml, members/index.md
Adds pravek as tsc voting member
Fixes #117
=> #117 add pravek as tsc voting member

meetings/2025-01-16/minutes.md, meetings/index.md
=> TSC 20250116 minutes

meetings/2025-01-30/minutes.md, meetings/index.md
=> 20250130 agenda

config.yaml, meetings/2025-02-13/2025-02-13 : TSC Minutes.ini, meetings/2025-02-13/minutes.md, meetings/2025-02-27/minutes.md, meetings/2025-03-13/minutes.md, meetings/index.md, members/index.md
* minutes for 2 previous meetings
* agenda for this week
* Adds Jake as TSC member to text list & access group for tsc
=> Minutes from previous meetings

members/index.md
Updated TSC lead for Matthias
removed myself as voting member
=> Update TSC lead to Matthias

meetings/2025-05-22/minutes.md
=> Minutes for 2025-05-22

CODEOWNERS
Implements https://github.com/pq-code-package/tsc/issues/62
=> Set pqcp-tsc as CODEOWNER of meetings/
